### ISSUE TITLE
Make npm edit command work like start command ?

### ISSUE THREAD

**Issue by Marxsal** [TiddlyWiki/TiddlyWikiLinks#31]
I'm already using port 8080. The` npm start` command used 8081. But the new npm edit uses port 8080 and throws an upcaptured error. Could this be tweaked to work like the start command? Thanks!

**Comment by Jermolene** [comment]
Hi @Marxsal the usual `npm start` command actually makes a static build of TWPub, and then uses a third party web server ("http-server") to actually serve it. It's "http-server" that has the capability to automatically choose an unused port. In order to offer the same capability in the `npm run edit` command we'd need to add the underlying capability to TW5. I think that would be a good idea in any case.
